# Generated by Django 5.1.2 on 2024-11-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antagonist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antagonist', to='atlantis.character')),
            ],
        ),
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='protagonist', to='atlantis.character')),
            ],
        ),
        migrations.CreateModel(
            name='Supporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supporting', to='atlantis.character')),
            ],
        ),
    ]
