# Generated by Django 5.1.2 on 2024-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0002_antagonist_protagonist_supporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
