# Generated by Django 5.1.2 on 2024-11-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlantis', '0003_character_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
